### ISSUE TITLE
bearer token 401

### ISSUE THREAD

**Issue by buonzz** [VaultGroup/api-samples#2]
Hello Guys,

for some account, im getting 401 error. We have acquired the bearer token via authorization code flow.
Im sure the api key is correct, because it works with the other accounts.

questions:

- is the bearer token expires after how much amount of hours/minutes?
- is there endpoint like for refresh token, where we could get another bearer token without requiring user-interaction?

any help will be really appreciated!

Thanks

**Comment by MattHealy** [comment]
Hi @buonzz , if you obtained the token via authorization flow, it will remain valid as long as the user is still active and hasn't changed their password. Once they change the password, all current bearer tokens for the user are invalidated. At that point you'll need to get the user to reauthenticate.

**Comment by buonzz** [comment]
thanks for the info :)
